---
sudo: false
dist: trusty
language: ruby
cache: bundler
# related to https://github.com/rubygems/rubygems/issues/2123
before_install:
  - 'rm -f Gemfile.lock'
  - 'gem update --system'
  - 'gem install bundler'
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: CHECK=test
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: CHECK=rubocop
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=ubuntu1804-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=ubuntu1604-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=centos7-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=debian9-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: true
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"

